services:
  - type: web
    name: pryvo-server
    rootDirectory: server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: STORAGE_DRIVER
        value: r2
      - key: EMAIL_PROVIDER
        value: emailjs
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_SECURE
        value: false
    secrets:
      - key: JWT_SECRET
      - key: JWT_REFRESH_SECRET
      - key: EMAILJS_SERVICE_ID
      - key: EMAILJS_TEMPLATE_ID
      - key: EMAILJS_PUBLIC_KEY
      - key: EMAILJS_PRIVATE_KEY
      - key: CLOUDFLARE_R2_ACCOUNT_ID
      - key: CLOUDFLARE_R2_ACCESS_KEY_ID
      - key: CLOUDFLARE_R2_SECRET_ACCESS_KEY
      - key: CLOUDFLARE_R2_BUCKET
      - key: CLOUDFLARE_R2_PREFIX
      - key: CLOUDFLARE_R2_PUBLIC_BASE_URL

