export const AppRoute = {
  OnboardingIntro: 'OnboardingIntro',
  SignUp: 'SignUp',
  SignIn: 'SignIn',
  Terms: 'Terms',
  Privacy: 'Privacy',
  PhoneInput: 'PhoneInput',
  OTPVerification: 'OTPVerification',
  Welcome: 'Welcome',
  BasicInfo: 'BasicInfo',
  DatingPreferences: 'DatingPreferences',
  PersonalDetails: 'PersonalDetails',
  Lifestyle: 'Lifestyle',
  ProfilePrompts: 'ProfilePrompts',
  MediaUpload: 'MediaUpload',
  SubscriptionUpsell: 'SubscriptionUpsell',
  HomeTabs: 'HomeTabs',
  Messages: 'Messages',
  Settings: 'Settings',
  HelpCentre: 'HelpCentre',
  ReportProblem: 'ReportProblem',
};
