buildscript {
    ext {
        buildToolsVersion = "36.0.0"
        minSdkVersion = 24
        compileSdkVersion = 36
        targetSdkVersion = 36
        ndkVersion = "27.1.12297006"
        kotlinVersion = "2.0.21"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:8.9.1")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
        classpath("com.google.gms:google-services:4.4.2")
        classpath fileTree(dir: "../node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/build/libs", include: ["*.jar"])
        classpath fileTree(dir: "../node_modules/@react-native/gradle-plugin/settings-plugin/build/libs", include: ["*.jar"])
        classpath fileTree(dir: "../node_modules/@react-native/gradle-plugin/shared/build/libs", include: ["*.jar"])
    }
    

}

allprojects {
    configurations.all {
        resolutionStrategy {
            force "androidx.core:core:1.15.0"
            force "androidx.core:core-ktx:1.15.0"
        }
    }
}
